const links: Record<string, string> = {
  ".NET": `https://dotnet.microsoft.com`,
  "ActionScript 3.0": `https://en.wikipedia.org/wiki/ActionScript`,
  "ActiveX": `https://en.wikipedia.org/wiki/ActiveX`,
  "AI agents": `https://en.wikipedia.org/wiki/Intelligent_agent`,
  "Android": `https://developer.android.com`,
  "AngularJS": `https://angularjs.org`,
  "Bun": `https://bun.sh`,
  "C#": `https://learn.microsoft.com/dotnet/csharp`,
  "C++": `https://isocpp.org`,
  "C/C++": `https://isocpp.org`,
  "COM": `https://learn.microsoft.com/windows/win32/com/component-object-model--com--portal`,
  "CSS": `https://developer.mozilla.org/docs/Web/CSS`,
  "CSS Modules": `https://github.com/css-modules/css-modules`,
  "Cursor": `https://cursor.com`,
  "Dart": `https://dart.dev`,
  "Docker": `https://www.docker.com`,
  "ESLint": `https://eslint.org`,
  "Fastify": `https://fastify.dev`,
  "Figma": `https://www.figma.com`,
  "Flash": `https://en.wikipedia.org/wiki/Adobe_Flash`,
  "Flutter": `https://flutter.dev`,
  "Git": `https://git-scm.com`,
  "GitHub Actions": `https://github.com/features/actions`,
  "GLSL": `https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)`,
  "HTML": `https://developer.mozilla.org/docs/Web/HTML`,
  "JavaScript": `https://developer.mozilla.org/docs/Web/JavaScript`,
  "Jest": `https://jestjs.io`,
  "Less": `https://lesscss.org`,
  "MCP": `https://modelcontextprotocol.io`,
  "Node.js": `https://nodejs.org`,
  "PHP": `https://www.php.net`,
  "Prettier": `https://prettier.io`,
  "Prisma": `https://www.prisma.io`,
  "Puppeteer": `https://pptr.dev`,
  "RAG": `https://en.wikipedia.org/wiki/Retrieval-augmented_generation`,
  "React": `https://react.dev`,
  "SCSS": `https://sass-lang.com`,
  "Silverlight": `https://en.wikipedia.org/wiki/Microsoft_Silverlight`,
  "Stylelint": `https://stylelint.io`,
  "tRPC": `https://trpc.io`,
  "tsdown": `https://tsdown.dev`,
  "tsx": `https://tsx.is`,
  "TypeScript": `https://www.typescriptlang.org`,
  "Vite": `https://vite.dev`,
  "Vitest": `https://vitest.dev`,
  "WebGL": `https://developer.mozilla.org/docs/Web/API/WebGL_API`,
  "WebSockets": `https://developer.mozilla.org/docs/Web/API/WebSockets_API`,
  "WPF": `https://learn.microsoft.com/dotnet/desktop/wpf`,
  "Zod": `https://zod.dev`,
};

const href = (name: string) => links[name];

export const TechLinks = { href };
