name: 🔁 CI

on:
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.task.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - name: 🏗️ build
            arg: build
          - name: 🧪 test
            arg: test
          - name: 📘 tsc
            arg: tsc
          - name: 🔍 eslint
            arg: eslint
          - name: ✨ prettier
            arg: prettier
          - name: 🎨 stylelint
            arg: stylelint
          - name: 📝 cspell
            arg: cspell
          - name: 📋 jscpd
            arg: jscpd
          - name: 🧹 knip
            arg: knip
          - name: 📄 markdownlint
            arg: markdownlint

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🔧 Setup repository
        uses: ./.github/actions/setup-repo

      - name: 🌐 Setup Chrome
        if: matrix.task.arg == 'build'
        run: bunx puppeteer browsers install chrome

      - name: ▶️ Run ${{ matrix.task.name }}
        run: bun do ${{ matrix.task.arg }}
